### ISSUE TITLE
recursion between file and file_link

### ISSUE THREAD

**Issue by marianoguerra** [stripe/openapi#137]
the file type has a field called links that has file_link items

the file_link type has a field called file which references the file type

I was trying to "normalize" the spec by replacing all schema $refs with the resolved values and got a recursion :)

**Comment by remi-stripe** [comment]
@marianoguerra This is expected behaviour and multiple resources in our API point to each other. A Charge has an `invoice` property that points to an Invoice which has a `charge` property that points to a Charge. A BalanceTransaction has a `source` property that can point to many object such as Charge or Refund or Payout which each have a `balance_transaction` property that points back to a BalanceTransaction.

Does that make sense?

**Comment by marianoguerra** [comment]
yep, just mentioned in case it wasn't the expected behaviour :)
