### ISSUE TITLE
Missing `dispute` on `charge`

### ISSUE THREAD

**Issue by marvinroger** [stripe/openapi#156]
Hi!

I noticed that the `charge` object has the `disputed` field documented, but the API also returns the expandable `dispute` field which could be `string | Stripe.Dispute | null`, but it's not documented (and therefore not typed in the Node.js client for example).

Could you please fix this?

Thanks!

**Comment by remi-stripe** [comment]
@marvinroger The `dispute` property on Charge was deprecated a few years ago and marked as undocumented. We haven't fully removed it from the API yet but it's discouraged to use it. The reason is that one Charge can now have multiple sequential Disputes attached to it so having `dispute: 'dp_123'` can be confusing and make you not realize that this can happen.
We recommend using the List Disputes [API](https://docs.stripe.com/api/disputes/list) with the `charge` or `payment_intent` parameter instead to find the Dispute(s) associated with one of those.
