### ISSUE TITLE
Request: Include `mandate` field in the `Source` object

### ISSUE THREAD

**Issue by tkbky** [stripe/openapi#40]
The `mandate` field appears in the request to create/update a `Source` object, but it's not inside the response. It's helpful to include it inside the `Source` object, to know what has been set.

**Comment by remi-stripe** [comment]
Hey @tkbky really sorry about the delay here, this one fell through the cracks. Since your issue was opened, Stripe shipped a dedicated [Mandate API](https://stripe.com/docs/api/mandates) that would reflect the information collected during payment or payment method setup.
I'm going to close this as it's quite stale and the Source API is considered mostly deprecated.
