### ISSUE TITLE
Some fields are coming back as null when they're not set to nullable

### ISSUE THREAD

**Issue by rdarder** [stripe/openapi#62]
Hi there!
We've been using your openapi spec to build our integration with stripe. We found that a few fields are not marked as nullable, though they come as null (or just unset) when getting those resources through your endpoints. In some cases the documentation string of those fields indicate that they might be null, but they spec doesn't say so.
I originally sent this as a PR (#60) so the diff is easier to read. Reposting here for visibility

**Comment by remi-stripe** [comment]
@rdarder `nullable: true` indicates that we could return the property as `subscription_proration_date: null`. On the other hand, if we don't return the property at all this is a different behaviour and instead of being _nullable_ it makes the property _optional_

Could you provide detailed examples of the cases you marked as nullable in the spec? Since our openapi spec is generated purely and automatically from our code it should already be complete and correct so we'd need to investigate further.

**Comment by rdarder** [comment]
Hi Remi, thanks for your response. 
Indeed, I was only paying attention to nullable, after taking required/optional fields into consideration, this works as expected. Sorry for the confusion and thank you!

**Comment by remi-stripe** [comment]
@rdarder No apologies necessary, our API is definitely complex now. I know the openapi spec (and all its quirks) quite well because we use that to generated most of our client libraries and we had to work around limitations and language specificities.

I'm glad to hear this removed the confusion so I'm going to close this out but please keep the feedback coming if you see anything wrong!
