### ISSUE TITLE
`product.type` is missing from the spec and the docs.

### ISSUE THREAD

**Issue by broccolihighkicks** [stripe/openapi#68]
The spec does not mention `product.type`, nor do the docs.

This causes issues as some of the other fields ("shippable") can only be set when type=good, but type defaults to `service`.

![image](https://user-images.githubusercontent.com/57859326/104347584-b2018a00-54f8-11eb-801c-09256d9f3c03.png)

**Comment by remi-stripe** [comment]
@broccolihighkicks Thanks for reaching out! `type` on `Product` has been considered deprecated for a while in our API. It used to separate products that were associated with a SKU (and worked with Orders) from recurring products associated with a Plan. Last year, we shipped the Price API to unify them all and `type` was made redundant at at that point.

I do agree it can be confusing when the API supports something that is undocumented. On the other hand, it can also be confusing when we document parameters that are discouraged from being used and where only a small number of historica integrations rely on it. That's why we recently undocumented `type` and removed it from the public openapi spec even though it is still supported (and will keep being supported for historical integrations).

Does this help clarify the situation a bit?

**Comment by broccolihighkicks** [comment]
Yes that makes sense thanks.

**Comment by broccolihighkicks** [comment]
How would I select all type=good with the new API?

**Comment by remi-stripe** [comment]
> How would I select all type=good with the new API?

The `type` filter still works even though it's undocumented if you're actively looking for Products of type good (with SKUs). Otherwise we don't recommend having that "distinction" anymore (though you can always use `metadata` to distinguish one from another)

**Comment by broccolihighkicks** [comment]
So the new way to have a "good" would be:

- Create `Product` (without setting type, so it defaults to type=service).
- Create a `Price` with `type=one_time`
	- Attach the `Product` to `Price` via `price.product=prod_id`

If `type` is no longer used, does that mean `package_dimensions`, `shippable` and other `type=good` only fields also should not be used? Should I be using `Product` at all?

**Comment by remi-stripe** [comment]
You have to use Products to use Prices since they are linked together whether you use Prices of type `recurring` or `one_time`. And yes `type` on `Product` is now obsolete and we discourage using all the "shipping" specific properties on products such as `package_dimensions` and `shippable` that you mentioned. For now, we recommend storing this on your end though we do have plans to add more of this into the future.
