### ISSUE TITLE
"invoicing" object property is missing from customer

### ISSUE THREAD

**Issue by bigjonroberts** [stripe/openapi#74]
We're using the generated C# services/client and are working around this for now using ExtraParams and a type derived from BaseOptions.

But this seems like something that should be in the spec?

**Comment by bigjonroberts** [comment]
We discovered how to access this API by setting the billing.invoicing settings in the dashboard and looking at the logs.

```
{
  "invoicing": {
    "email_to": [
      "mainemailaddress@test.com"
    ],
    "email_cc": [
      "another@test.com",
      "yetanother@test.io"
    ]
  }
}
```

**Comment by remi-stripe** [comment]
@bigjonroberts The `invoicing` parameter is not in our public API and is something only available to the Dashboard today. Since it's not public, it's expected that it's not in our openapi spec or our client libraries. 
I strongly recommend **not** relying on this if you found a way to make it work since we could break it at any time as something that is Dashboard only.

I agree it's a useful feature but it won't be in the spec until we decide to ship public which I recommend flagging your interest for with our support team: https://support.stripe.com/contact/email

**Comment by jonahgeorge** [comment]
Related:
- https://github.com/stripe/stripe-java/issues/1005
- https://github.com/stripe/stripe-dotnet/issues/1599
- https://github.com/stripe/stripe-ruby/issues/781
- https://github.com/stripe/stripe-php/issues/595
- https://github.com/stripe/stripe-dotnet/issues/1641
